name: text-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - blas=1.0=mkl
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hf0e25f4_1
  - chardet=3.0.4=py36_1003
  - cryptography=2.6.1=py36h72c5cf5_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - freetype=2.10.0=he983fc9_0
  - idna=2.8=py36_1000
  - intel-openmp=2019.3=199
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - libblas=3.8.0=4_mkl
  - libcblas=3.8.0=4_mkl
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=4_mkl
  - libpng=1.6.36=h84994c4_1000
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h648cc4a_1001
  - mkl=2019.1=144
  - munch=2.3.2=py_0
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.9.0=h6bb024c_0
  - numpy=1.16.2=py36h7fc5cc3_0
  - olefile=0.46=py_0
  - openblas=0.3.5=ha44fe06_0
  - openssl=1.1.1b=h14c3975_1
  - pandas=0.24.2=py36hf484d3e_0
  - pillow=6.0.0=py36he7afcd5_0
  - pip=19.0.3=py36_0
  - pycparser=2.19=py36_1
  - pyopenssl=19.0.0=py36_0
  - pysocks=1.6.8=py36_1002
  - python=3.6.7=h381d211_1004
  - python-dateutil=2.8.0=py_0
  - pytorch=1.0.1=cuda100py36he554f03_0
  - pytz=2018.9=py_0
  - pyzmq=18.0.1=py36h0e1adb2_0
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py36_1000
  - scikit-learn=0.20.3=py36ha8026db_1
  - scipy=1.2.1=py36h09a28d5_1
  - setuptools=41.0.0=py36_0
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=h67949de_1001
  - tk=8.6.9=h84994c4_1001
  - torchfile=0.1.0=py_0
  - tornado=6.0.2=py36h516909a_0
  - tqdm=4.31.1=py_0
  - urllib3=1.24.1=py36_1000
  - visdom=0.1.8.8=0
  - websocket-client=0.56.0=py36_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.2.5=hf484d3e_1006
  - zlib=1.2.11=h14c3975_1004
  - pip:
    - boto3==1.9.130
    - botocore==1.12.130
    - docutils==0.14
    - jmespath==0.9.4
    - pytorch-pretrained-bert==0.6.1
    - regex==2019.4.9
    - s3transfer==0.2.0

