name: text-classification
channels:
  - defaults
  - forge
dependencies:
  - tqdm==4.42.1
  - pandas==1.0.0
  - scikit-learn==0.22.1
  - matplotlib==3.1.2
  - seaborn==0.10.0
  - python=3.6
  - spacy==2.0.16
  - boto3==1.12.0
  - munch==2.5.0
  - pip:
    - docker==4.2.0
    - transformers==2.5.1
